# Generated by Django 6.1.1 on 2026-09-29 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('mca', 'MCA'), ('bca', 'BCA'), ('12th', '12th Standard'), ('10th', '10th Standard'), ('cert', 'Certification')], default='mca', max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('score_label', models.CharField(default='CGPA / Percentage', max_length=50)),
                ('score_value', models.CharField(max_length=50)),
                ('curriculum', models.TextField(default='Core Software Engineering; Database Architecture; Web Technologies', help_text='Separate points with semicolons (;)')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Education Record',
                'verbose_name_plural': 'Education Records',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sachin Lad', max_length=100)),
                ('title', models.CharField(default='Full-Stack Developer', max_length=150)),
                ('tagline', models.CharField(default='Building scalable web applications with Python & Django.', max_length=255)),
                ('bio', models.TextField(default='Seeking opportunities in the IT industry where I can apply technical skills, problem-solving abilities, and passion for technology while contributing to organizational growth.')),
                ('degree_badge', models.CharField(default='MCA', max_length=50)),
                ('email', models.EmailField(default='slad20401@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91 7487095241', max_length=20)),
                ('whatsapp', models.CharField(default='917487095241', max_length=20)),
                ('address', models.CharField(default='B-203 Nandanvan, Society Motera Road, Sabarmati, Ahmedabad - 380005', max_length=255)),
                ('linkedin_url', models.URLField(default='https://www.linkedin.com/in/sachin-lad-a75a61')),
                ('github_url', models.URLField(default='https://github.com/SachinLad')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('status_text', models.CharField(default='Available for Opportunities', max_length=100)),
            ],
            options={
                'verbose_name': 'Profile Information',
                'verbose_name_plural': 'Profile Information',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(default='Python, Django, HTML, CSS, JavaScript', max_length=150)),
                ('tag', models.CharField(default='Django & SQLite', max_length=100)),
                ('date_label', models.CharField(default='Jan 2024', max_length=50)),
                ('description', models.TextField()),
                ('features', models.TextField(default='Secure login for admin and user; Manage schedules; Send updates and notifications', help_text='Separate points with semicolons (;)')),
                ('tech_stack', models.CharField(default='Python, Django, HTML5, CSS3, JavaScript, SQLite', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True, help_text='Live project preview URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(default='code', help_text='e.g. code, database, tool, brain, server', max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_color', models.CharField(default='cyan', help_text='e.g. red, cyan, emerald, amber, purple', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio_app.skillcategory')),
            ],
        ),
    ]
